export const BOOK_ADD_SUCCESS = 'BOOK_ADD_SUCCESS'
export const BOOK_ADD_FAIL = 'BOOK_ADD_FAIL';

export const BOOK_ADD_SUCCESS_CLEAR = 'BOOK_ADD_SUCCESS_CLEAR'
export const BOOK_ADD_FAIL_CLEAR = 'BOOK_ADD_FAIL_CLEAR';

export const BOOK_GET_SUCCESS = 'BOOK_GET_SUCCESS';

export const GET_SINGLE_BOOK ='GET_SINGLE_BOOK'
export const GET_SUGGESTED_BOOK = 'GET_SUGGESTED_BOOK'