export const REVIEW_ADD_SUCESS = 'REVIEW_ADD_SUCCESS'
export const REVIEW_ADD_SUCESS_CLEAR = 'REVIEW_ADD_SUCCESS_CLEAR'
export const REVIEW_ADD_FAIL = 'REVIEW_ADD_FAIL'
export const REVIEW_ADD_FAIL_CLEAR = 'REVIEW_ADD_FAIL_CLEAR'

export const REVIEW_GET_SUCCESS = 'REVIEW_GET_SUCCESS'
export const REVIEW_GET_FAIL = 'REVIEW_GET_FAIL'